### ISSUE TITLE
Log4j Bug

### ISSUE THREAD

**Issue by ghost** [CobbleSword/BurritoSpigot#10]
I still can use logger in chat: i just did this ${date:yyyy}
![image](https://user-images.githubusercontent.com/95770249/145683383-fc1bcb88-4883-4989-8140-eef587e3dc7e.png)

Here is my console output
![image](https://user-images.githubusercontent.com/95770249/145683400-bebc2581-5aed-4deb-b3b3-ae3997954fa6.png)

**Comment by CyberFlameGO** [comment]
Oh? What chat plugin are you using, and can you paste the output of `/ver` please?

**Comment by ghost** [comment]
I installed the latest version that you sent
![image](https://user-images.githubusercontent.com/95770249/145683524-1a240063-4901-40a8-9ae2-da12b430e0d2.png)

**Comment by ghost** [comment]
BedWars1058's chat system

**Comment by CyberFlameGO** [comment]
My apologies, this is an issue with the workflow.

**Comment by ghost** [comment]
> My apologies, this is an issue with the workflow.

so it's not the BurriotoSpigot's fault?

**Comment by CyberFlameGO** [comment]
It’s to do with the workflow. @HeathLoganCampbell @Elierrr

**Comment by ghost** [comment]
It isn't a problem with the workflow, it's that Github isn't showing the correct latest version.

@Sxhqil For now, use [this](https://github.com/CobbleSword/BurritoSpigot/releases/download/BurritoSpigot-342028d7b706881c3bcc83dcc399eac8004631f8/BurritoSpigot.jar).

**Comment by ghost** [comment]
> It isn't a problem with the workflow, it's that Github isn't showing the correct latest version.
> 
> @Sxhqil For now, use [this](https://github.com/CobbleSword/BurritoSpigot/releases/download/BurritoSpigot-342028d7b706881c3bcc83dcc399eac8004631f8/BurritoSpigot.jar).

Thanks it's now working fine
