### ISSUE TITLE
Crashes Randomly

### ISSUE THREAD

**Issue by HowardZHY** [CobbleSword/BurritoSpigot#21]
**Describe the bug**
Crashes Randomly ,especially when player join
**To Reproduce**
Crashes Randomly, especially when player join

**Expected behavior**
No crash.

**What is your Java Version?**
JDK8u311

**What is the error you see? (Please not an image)**
**What's your plugin list?**
[crash-2022-01-15_18.51.54-server.txt](https://github.com/CobbleSword/BurritoSpigot/files/7874822/crash-2022-01-15_18.51.54-server.txt)
[crash-2022-01-15_18.55.16-server.txt](https://github.com/CobbleSword/BurritoSpigot/files/7874823/crash-2022-01-15_18.55.16-server.txt)
[crash-2022-01-15_17.30.41-server.txt](https://github.com/CobbleSword/BurritoSpigot/files/7874824/crash-2022-01-15_17.30.41-server.txt)
[crash-2022-01-15_17.58.10-server.txt](https://github.com/CobbleSword/BurritoSpigot/files/7874825/crash-2022-01-15_17.58.10-server.txt)
[crash-2022-01-15_18.03.21-server.txt](https://github.com/CobbleSword/BurritoSpigot/files/7874826/crash-2022-01-15_18.03.21-server.txt)
[crash-2022-01-15_18.08.39-server.txt](https://github.com/CobbleSword/BurritoSpigot/files/7874827/crash-2022-01-15_18.08.39-server.txt)
[crash-2022-01-15_18.48.39-server.txt](https://github.com/CobbleSword/BurritoSpigot/files/7874828/crash-2022-01-15_18.48.39-server.txt)

**Additional context**
temperately no

**Comment by HeathLoganCampbell** [comment]
I'm struggling to reproduce this sorry

**Comment by HowardZHY** [comment]
> I'm struggling to reproduce this sorry

I'm sure it's a problem by plugin Client Detector , I removed that plugin and no crash.
