### ISSUE TITLE
Some Performance Improves from Nacho

### ISSUE THREAD

**Issue by HowardZHY** [CobbleSword/BurritoSpigot#22]
especially chunk patches  
eg:
chunk:
    # The amount of threads used for chunks
    threads: 3
  # Enable Fast Math usage.
  enable-fastmath: true
  # Kicks players if they try to do an illegal action (e.g. using a creative mode action while not in creative mode.)
  kick-on-illegal-behavior: true

PS:[Nacho-0014] stop timings crashing the server but still print the error - this happened in Torch , but I wonder is there anything we can learn from Torch's multithread

**Comment by HeathLoganCampbell** [comment]
Fast Math isn't really an optimization, I have benchmarked it, it's more marketing that an optimization

**Comment by HeathLoganCampbell** [comment]
and is kick-on-illegal-behavior isn't an optimization, it's just a bad data catch

**Comment by MWHunter** [comment]
Can confirm as an anticheat dev that fastmath is fucking stupid and does absolutely nothing except cause suffering for other devs expecting math to be correct

**Comment by HowardZHY** [comment]
just add this:
chunk:
# The amount of threads used for chunks
threads: 3
