### ISSUE TITLE
Don't archive this

### ISSUE THREAD

**Issue by HowardZHY** [CobbleSword/BurritoSpigot#29]
this is the most stable taco folk, should accept new fix patches

**Comment by ghost** [comment]
I don't think is the most stable but was archived because there's no enough time to provide support

**Comment by HowardZHY** [comment]
> I don't think is the most stable but was archived because there's no enough time to provide support

at least more stable than torch, fox and other stuffs

**Comment by HeathLoganCampbell** [comment]
This bad boi isn't archieved
